sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"

install:
  - pip install -e .
script:
  - py.test

cache:
  directories:
    - $HOME/.cache/pip/http

deploy:
  provider: pypi
  distributions: 'sdist bdist_wheel'
  on:
    branch: 'master'
    tags: true
  password:
    secure: >-
      Yg5m1M3mhezSOdEA2bfQ/0tU4T5/kh9DjH11lvNVZA7QSY4AWp0Ri
      38Ea5bk7HP24nlFAXFTrrWr5UJ2ZjdJ/P04tFIWA4yP1H+HU9IF8/
      3FSauKjT2uzd0Cy7aP3PB5k2RFNPdtmHqCJr9o5yjAgT74Pv/dM5k
      t8Qj3h5szdpI=
  user: 'pytest-catchlog-ci'
